// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "company-micro/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CompanyUsecase is an autogenerated mock type for the CompanyUsecase type
type CompanyUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, company
func (_m *CompanyUsecase) Create(c context.Context, company *domain.Company) error {
	ret := _m.Called(c, company)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Company) error); ok {
		r0 = rf(c, company)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByName provides a mock function with given fields: c, name
func (_m *CompanyUsecase) DeleteByName(c context.Context, name string) (int64, error) {
	ret := _m.Called(c, name)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(c, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(c, name)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: c, name
func (_m *CompanyUsecase) GetByName(c context.Context, name string) (domain.Company, error) {
	ret := _m.Called(c, name)

	var r0 domain.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Company, error)); ok {
		return rf(c, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Company); ok {
		r0 = rf(c, name)
	} else {
		r0 = ret.Get(0).(domain.Company)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUUID provides a mock function with given fields: c, companyUUID
func (_m *CompanyUsecase) GetByUUID(c context.Context, companyUUID string) (domain.Company, error) {
	ret := _m.Called(c, companyUUID)

	var r0 domain.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Company, error)); ok {
		return rf(c, companyUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Company); ok {
		r0 = rf(c, companyUUID)
	} else {
		r0 = ret.Get(0).(domain.Company)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, companyUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCompanyUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewCompanyUsecase creates a new instance of CompanyUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCompanyUsecase(t mockConstructorTestingTNewCompanyUsecase) *CompanyUsecase {
	mock := &CompanyUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
