version: "3.8"

services:
  company_micro:
    build:
      context: .
      dockerfile: Dockerfile
    image: company_micro
    container_name: company_micro
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8081:8081
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
